config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  after_create_commit { broadcast_prepend_to 'tweets'}
  after_update_commit { broadcast_replace_to 'tweets' }
  after_destroy_commit { broadcast_remove_to 'tweets'}
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: { tweet: @tweet}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :likes_count, :retweets_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHotwire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= turbo_include_tags %>
    <%# <%= stimulus_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.haml
= form_with model: tweet, id: dom_id(tweet) do |f|
  - if tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - tweet.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/tweets/_tweet.html.haml
= turbo_frame_tag dom_id(tweet) do
  .card.card-body
    = tweet.body

  .mt-2
    = link_to "Likes (#{tweet.likes_count})", '#', class: 'btn btn-primary'
    = link_to "Retweets (#{tweet.retweets_count})", '#', class: 'btn btn-primary'
    = link_to "Edit", edit_tweet_path(tweet)

app/views/tweets/edit.html.haml
%h1 Editing tweet

= turbo_frame_tag dom_id(@tweet) do
  .card.card-body
    = render 'form', tweet: @tweet
    = link_to 'CANCEL', @tweet

app/views/tweets/index.html.haml
%h1 Listing tweets
= turbo_stream_from "tweets"

= turbo_frame_tag "tweet_form" do
  = render 'form', tweet: @tweet


= turbo_frame_tag "tweets" do
  = render @tweets

%br

= link_to 'New Tweet', new_tweet_path

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form', tweet: @tweet

= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice

= turbo_frame_tag dom_id(@tweet) do
  = render @tweet

= link_to 'Edit', edit_tweet_path(@tweet)
\|
= link_to 'Back', tweets_path